name: pls-dataset

channels:
  - conda-forge
  - pip
  - rdkit

# TODO: Make sure that this is correct.
dependencies:
  - python>=3.10
  - matplotlib>=3.1.3
  - numpy>=1.18.1
  - pandas>=1.0.3
  - pip>=20.0.2
  - rdkit>=2020.03.1.0
  - scipy>=1.4.1
  - scikit-optimize>=0.9.0
  - matplotlib
  - pandas
  - scikit-learn
  - numpy
  - rdkit-pypi
  - ipython
  - scikit-optimize
  - seaborn
  - xgboost
  - ngboost
  - mordred
