name: pls-dataset

channels:
  - conda-forge
  - pip
  - rdkit
  - bioconda

# TODO: Make sure that this is correct.
dependencies:
  - python=3.10
  - numpy=1.23.5
  - pandas>=1.0.3
  - pip>=20.0.2
  - rdkit=2024.3.3
  - scipy>=1.4.1
  - scikit-optimize>=0.9.0
  - matplotlib
  - pandas
  - scikit-learn
  - numpy
  - ipython
  - scikit-optimize
  - seaborn
  - xgboost
  - ngboost
  - mordred=1.2.0
  - Pandarallel
  - openpyxl
  - gpytorch
