name: Mixed GP kernels for Molecular Fingerprints and Continuous Parameters


channels:
  - conda-forge
  - rdkit
  - bioconda
  - defaults
  - pip

dependencies:
  - python>=3.10.0,<=3.11.0
  - numpy
  - pandas
  - pip
  - rdkit>=2024
  - scipy
  - scikit-optimize
  - scikit-learn
  - matplotlib
  - ipython
  - seaborn
  - xgboost
  - ngboost
  - mordred>=1.2.0
  # - openpyxl
  # - gpytorch


